apiVersion: v1
kind: Namespace
metadata:
  name: time-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: time-api
  name: time-api-deployment
  namespace: time-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-api
  template:
    metadata:
      labels:
        app: time-api
    spec:
      containers:
      - name: time-api
        #image: mimi0248/time-api:latest
        image: us-central1-docker.pkg.dev/massive-jet-434317-i3/project/time-api:latest
        imagePullPolicy: Always
        command: ["python", "app2.py"] 
        ports:
        - containerPort: 8080
       # resources:
        #  limits:
         #   cpu: "300m"
          #  memory: "300Mi"
      imagePullSecrets:
      - name: gcr-json-key

---
apiVersion: v1
kind: Service
metadata:
  name: time-api-service
  namespace: time-api
spec:
  type: LoadBalancer
  selector:
    app: time-api
  ports:
  - protocol: TCP
    port: 8080                    # Port accessible within the cluster
    targetPort: 8080              # Port on the container
    #nodePort: 30007
    #ClusterIP: 8001